Update for gap 4.9

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -17,18 +17,18 @@ fi
 
 echo "Architecture is $GAParch (from sysinfo.gap)"
 
-GAPARCH=$GAPPATH/bin/$GAParch
+if ! test -e $GAPPATH/gac; then
+  echo "Cannot find 'gac' at " $GAPPATH
+  exit 1
+fi;
 
-. $GAPARCH/sysinfo.gap
-
-echo "C compiler is $c_compiler (from $GAParch/sysinfo.gap)"
-
+eval $(grep '^CC=' $GAPPATH/gac)
 
 # Let's find a C++ standard library. In practice there are two.
 
 func_get_libname () {
   for flag in -lstdc++ -llibc++; do
-    if echo "#include <vector>\n#include<string.h>\n#include<string>\n int main(void) { std::vector<int> v(5); }" | $c_compiler $flag -x c++  -c - -o /dev/null 1>/dev/null 2>/dev/null; then
+    if echo "#include <vector>\n#include<string.h>\n#include<string>\n int main(void) { std::vector<int> v(5); }" | $CC $flag -x c++  -c - -o /dev/null 1>/dev/null 2>/dev/null; then
         CPPLIB="$flag"
         return 0
     fi
@@ -55,7 +55,7 @@ echo "Makefile successfully created."
 
 echo '#!/bin/bash' > gapcpp.vars
 echo export GAPARCH=\"$GAParch\" >> gapcpp.vars
-echo export CC=$c_compiler >> gapcpp.vars
+echo export CC=$CC >> gapcpp.vars
 echo export CXX=c++ >> gapcpp.vars
 echo export VALGRIND=\"$VALGRIND\" >> gapcpp.vars
 echo export DEBUGFLAGS=\"$DEBUGFLAGS\" >> gapcpp.vars
